GET http://localhost:3001/api/notes

###
# POST
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS code rest client is pretty handy tool",
    "important": true
}

###
# DELETE
DELETE http://localhost:3001/api/notes/2

###
PUt http://localhost:3001/api/notes/6536395d23b27186bf6c7d40
Content-Type: application/json

{
    "content": "This id has updated",
    "important": true
}

###
# Login
POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "taha akinci",
    "password": "deneme123"
}