GET http://localhost:3001/api/notes

###
# POST
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS code rest client is pretty handy tool",
    "important": true
}

###
# DELETE
DELETE http://localhost:3001/api/notes/2

